# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Allergen.destroy_all
Flavor.destroy_all

Allergen.create([
  {
    name: "Milk"
  },
  {
    name: "Wheat"
  },
  {
    name: "Egg"
  },
  {
    name: "Tree Nuts"
  },
  {
    name: "Peanut"
  },
  {
    name: "Soy"
  },
])

Flavor.create(
  name: "Cable Car Chocolate",
  url: "http://www.sciencekids.co.nz/images/experiments/chocolate240.jpg",
  non_dairy: false,
  ingredients: "Pasteurized Non Fat Milk, Liquid Sugar (Sugar, Water), Pasteurized Sweet Cream Buttermilk, Pasteurized and Cultured Non Fat Milk, Corn Syrup, Cocoa (Processed with Allkali), Whey, Contains Less Than 1% Of Non Fat Dry Milk, Cocoa (Processed with Alkali), Milk Protein Isolate, Cellulose Gum, Guar Gum, Carrageenan, Modified Food Starch, Pectin, Natural and Artificial Flavors. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
  calories: "100",
  calories_from_fat: "5",
  total_fat: "0",
  saturated_fat: "0",
  trans_fat: "0",
  cholesterol: "0",
  sodium: "70",
  total_carbohydrate: "22",
  dietary_fiber: "0",
  sugar: "17",
  sugar_alcohols: "0",
  protein: "3",
  vitamin_a: "0",
  vitamin_c: "0",
  calcium: "10",
  iron: "6",
  )

 Flavor.create(
  name: "Salted Butterscotch",
  url: "http://saltrevolution.com/wp-content/uploads/2013/11/Sea-Salt-Caramels-300x240.jpg",
  non_dairy: false,
  ingredients: "Pasteurized Non Fat Milk, Liquid Sugar (Sugar, Water), Pasteurized Sweet Cream Buttermilk, Pasteurized and Cultured Non Fat Milk, Caramel Base (Corn Syrup, Butter (cream, salt), Water, Sugar, Sweetened Condensed Skim Milk (Condensed Skim Milk, Sugar), Natural Flavor, Caramel Color, Annatto Extract (for color), Salt, Carrageenan), Salted Caramel Base (Water, Sugar, Brown Sugar, Natural and Artificial Flavors, Modified Food Starch, Salt, Citric Acid), Corn Syrup, Non Fat Dry Milk, Cream, Whey, Sweetened Pasteurized Egg Yolks (Egg Yolks, Sugar), Contains less than 1% of Caramel Color, Mono- & Diglycerides, Cellulose Gum, Guar Gum, Modified Food Starch, Carrageenan, Pectin. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
  calories: "120",
  calories_from_fat: "20",
  total_fat: "2",
  saturated_fat: "1",
  trans_fat: "0",
  cholesterol: "20",
  sodium: "85",
  total_carbohydrate: "23",
  dietary_fiber: "0",
  sugar: "19",
  sugar_alcohols: "0",
  protein: "3",
  vitamin_a: "0",
  vitamin_c: "0",
  calcium: "10",
  iron: "0",
  )
  

 Flavor.create(
  name: "Country Vanilla",
  url: "https://www.vaporstop.com/Web/_site/_img/_products/vanilla/vanilla-1.png",
  non_dairy: false,
  ingredients: "Pasteurized Non Fat Milk, Liquid Sugar (Sugar, Water), Pasteurized Sweet Cream Buttermilk, Corn Syrup, Pasteurized and Cultured Non Fat Milk, Whey, Contains Less Than 1% Of Mono- & Diglycerides, Cellulose Gum, Guar Gum, Non Fat Dry Milk, Natural and Artificial Flavors, Modified Food Starch, Carrageenan, Pectin, Annatto Extract (For Color). Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
  calories: "100",
  calories_from_fat: "5",
  total_fat: "0",
  saturated_fat: "0",
  trans_fat: "0",
  cholesterol: "5",
  sodium: "75",
  total_carbohydrate: "22",
  dietary_fiber: "0",
  sugar: "18",
  sugar_alcohols: "0",
  protein: "2",
  vitamin_a: "0",
  vitamin_c: "0",
  calcium: "10",
  iron: "0",
  )

 Flavor.create(
  name: "Cotton Candy",
  url: "http://cdn2.bigcommerce.com/server4600/aw20as/products/217/images/419/Blueberry_cotton_candy__46629__56912.1427976127.490.588.jpg?c=2",
  non_dairy: false,
  ingredients: "Pasteurized Skim Milk, Liquid Sugar (Sugar, Water), Pasteurized Sweetcream Buttermilk, Pasteurized and Cultured Skim Milk, Corn Syrup, Whey, Nonfat Dry Milk, Contains Less Than 1% of Milk Protein Isolate, Cellulose Gum, Guar Gum, Carrageenan, Natural and Artificial Flavors, Modified Food Starch, Pectin, Blue #1, Purified Stevia Extract. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
  calories: "90",
  calories_from_fat: "0",
  total_fat: "0",
  saturated_fat: "0",
  trans_fat: "0",
  cholesterol: "5",
  sodium: "65",
  total_carbohydrate: "20",
  dietary_fiber: "0",
  sugar: "17",
  sugar_alcohols: "0",
  protein: "3",
  vitamin_a: "0",
  vitamin_c: "0",
  calcium: "10",
  iron: "0",
  )
 Flavor.create(
  name: "New York Cheesecake (no sugar added)",
  url: "https://s-media-cache-ak0.pinimg.com/236x/03/74/b7/0374b748698c8af5a467268225ab543c.jpg",
  non_dairy: false,
  ingredients: "Pasteurized Skim Milk, Liquid Sugar (Sugar, Water), Pasteurized Sweetcream Buttermilk, Pasteurized and Cultured Skim Milk, Corn Syrup, Whey, Nonfat Dry Milk, Contains Less Than 1% of Milk Protein Isolate, Cellulose Gum, Guar Gum, Carrageenan, Natural and Artificial Flavors, Modified Food Starch, Pectin, Blue #1, Purified Stevia Extract. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
  calories: "80",
  calories_from_fat: "0",
  total_fat: "0",
  saturated_fat: "0",
  trans_fat: "0",
  cholesterol: "5",
  sodium: "80",
  total_carbohydrate: "18",
  dietary_fiber: "0",
  sugar: "6",
  sugar_alcohols: "4",
  protein: "0",
  vitamin_a: "0",
  vitamin_c: "0",
  calcium: "15",
  iron: "0",
  )

 Flavor.create(
  name: "Strawberry (no sugar added)",
  url: "http://product-images.highwire.com/10459345/albion-strawberry_240.jpg",
  non_dairy: false,
  ingredients: "Pasteurized Non Fat Milk, Pasteurized Sweet Cream Buttermilk, Pasteurized and Cultured Non Fat Milk, Maltodextrin, Sorbitol, Whey, Strawberry Base (Water, Natural Flavor, Strawberries, Citric Acid, Locust Bean Gum, Red #3, Red #40, Blue #1), Non Fat Dry Milk, Contain Less Than 1% Of Mono- & Diglycerides, Cellulose Gum, Guar Gum, Cellulose Gel, Modified Food Starch, Carrageenan, Pectin, Sucralose, Acesulfame Potassium. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
  calories: "80",
  calories_from_fat: "0",
  total_fat: "0",
  saturated_fat: "0",
  trans_fat: "0",
  cholesterol: "0",
  sodium: "80",
  total_carbohydrate: "17",
  dietary_fiber: "0",
  sugar: "6",
  sugar_alcohols: "4",
  protein: "3",
  vitamin_a: "0",
  vitamin_c: "0",
  calcium: "10",
  iron: "0",
  )

 Flavor.create(
  name: "Cookies 'n Cream",
  url: "https://s-media-cache-ak0.pinimg.com/236x/50/78/fe/5078fe435061b9c58a4af85df97d0b27.jpg",
  non_dairy: false,
  ingredients: "Pasteurized Non Fat Milk, Pasteurized Sweet Cream Buttermilk, Liquid Sugar (Sugar, Water), Corn Syrup, Pasteurized and Cultured Non Fat Milk, Whey, Maltodextrin, Cake Base (Wheat Flour, Powdered Sugar, Shortening (Partially Hydrogenated Soybean Oil), Cocoa, Sugar, Caramel Color, Baking Soda, Salt, Natural Vanilla Flavor, Ammonium Bicarbonate), Marshmallow Syrup (Corn Syrup, Sugar, Water, Egg Whites, Artificial Flavors, Xanthan Gum, Lactic Acid, Salt), Contains Less Than 1% Of Mono- & Diglycerides, Cellulose Gum, Guar Gum, Natural and Artificial Flavors, Non Fat Dry Milk, Cocoa (Processed with Alkali), Modified Food Starch, Carrageenan, Pectin. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
  calories: "110",
  calories_from_fat: "5",
  total_fat: "0.5",
  saturated_fat: "0",
  trans_fat: "0",
  cholesterol: "5",
  sodium: "85",
  total_carbohydrate: "25",
  dietary_fiber: "0",
  sugar: "18",
  sugar_alcohols: "0",
  protein: "3",
  vitamin_a: "0",
  vitamin_c: "0",
  calcium: "10",
  iron: "0",
  )

 Flavor.create(
  name: "Cake Batter",
  url: "https://highdesertvapes.com/product_images/x/480/Cake_Batter_Flavor__23882_std.jpg",
  non_dairy: false,
  ingredients: "Pasteurized Non Fat Milk, Pasteurized Sweet Cream Buttermilk, Liquid Sugar (Sugar, Water), Corn Syrup, Pasteurized and Cultured Non Fat Milk, Whey, Maltodextrin, Cake Base (Wheat Flour, Powdered Sugar, Shortening (Partially Hydrogenated Soybean Oil), Cocoa, Sugar, Caramel Color, Baking Soda, Salt, Natural Vanilla Flavor, Ammonium Bicarbonate), Marshmallow Syrup (Corn Syrup, Sugar, Water, Egg Whites, Artificial Flavors, Xanthan Gum, Lactic Acid, Salt), Contains Less Than 1% Of Mono- & Diglycerides, Cellulose Gum, Guar Gum, Natural and Artificial Flavors, Non Fat Dry Milk, Cocoa (Processed with Alkali), Modified Food Starch, Carrageenan, Pectin. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
  calories: "110",
  calories_from_fat: "5",
  total_fat: "0.5",
  saturated_fat: "0",
  trans_fat: "0",
  cholesterol: "5",
  sodium: "85",
  total_carbohydrate: "25",
  dietary_fiber: "0",
  sugar: "18",
  sugar_alcohols: "0",
  protein: "3",
  vitamin_a: "0",
  vitamin_c: "0",
  calcium: "10",
  iron: "0",
  )

  Flavor.create(
   name: "Coconut",
   url: "http://cdn.shopify.com/s/files/1/0676/8653/products/coconut1_large.jpg?v=1423408260",
   non_dairy: false,
   ingredients: "Pasteurized Non Fat Milk, Liquid Sugar (Sugar, Water), Pasteurized Sweet Cream Buttermilk, Pasteurized and Cultured Non Fat Milk, Corn Syrup, Whey, Coconut Base (Sugar, Coconut, Water, Natural Flavor, Modified Food Starch), Contains Less Than 1% Of Non Fat Dry Milk, Mono- & Diglycerides, Cellulose Gum, Guar Gum, Modified Food Starch, Carrageenan, Pectin. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium",
   calories: "110",
   calories_from_fat: "5",
   total_fat: "0.5",
   saturated_fat: "0.5",
   trans_fat: "0",
   cholesterol: "0",
   sodium: "70",
   total_carbohydrate: "22",
   dietary_fiber: "0",
   sugar: "18",
   sugar_alcohols: "0",
   protein: "2",
   vitamin_a: "0",
   vitamin_c: "0",
   calcium: "10",
   iron: "0",
   )

   Flavor.create(
    name: "Hawaiian Pineapple",
    url: "http://render.fineartamerica.com/images/images-print-search/images-medium-5/fresh-pineapple-bernard-jaubert.jpg",
    non_dairy: false,
    ingredients: "Pasteurized Non Fat Milk, Liquid Sugar (Sugar, Water), Pasteurized Sweet Cream Buttermilk, Pasteurized and Cultured Non Fat Milk, Corn Syrup, Pineapple Base (Water, Pineapple Juice Concentrate, Natural Flavor, Fructose, Citric Acid, Modified Food Starch, Sugar, Sodium Citrate, Turmeric (For Color)), Whey, Contains Less Than 1% Of Non Fat Dry Milk, Mono- & Diglycerides, Cellulose Gum, Guar Gum, Modified Food Starch, Carrageenan, Pectin. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
    calories: "100",
    calories_from_fat: "5",
    total_fat: "0",
    saturated_fat: "0",
    trans_fat: "0",
    cholesterol: "0",
    sodium: "70",
    total_carbohydrate: "22",
    dietary_fiber: "0",
    sugar: "17",
    sugar_alcohols: "0",
    protein: "2",
    vitamin_a: "0",
    vitamin_c: "0",
    calcium: "10",
    iron: "0",
    )

    Flavor.create(
     name: "Pistachio",
     url: "http://www.in.all.biz/img/in/catalog/middle/314179.jpeg?rrr=1",
     non_dairy: false,
     ingredients: "Pasteurized Non Fat Milk, Liquid Sugar (Sugar, Water), Pasteurized Sweet Cream Buttermilk, Corn Syrup, Whey, Pasteurized and Cultured Non Fat Milk, Whey, Contains Less Than 1% Of Mono- & Diglycerides, Cellulose Gum, Guar Gum, Non Fat Dry Milk, Natural and Artificial Flavors, Modified Food Starch, Carrageenan, Pectin. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
     calories: "100",
     calories_from_fat: "5",
     total_fat: "0",
     saturated_fat: "0",
     trans_fat: "0",
     cholesterol: "5",
     sodium: "75",
     total_carbohydrate: "22",
     dietary_fiber: "0",
     sugar: "18",
     sugar_alcohols: "0",
     protein: "2",
     vitamin_a: "0",
     vitamin_c: "0",
     calcium: "10",
     iron: "0",
     )

     Flavor.create(
      name: "Peanut Butter",
      url: "http://www.snackinginsneakers.com/wp-content/uploads/2014/11/Peanut-butter-Love-260x260.jpg",
      non_dairy: false,
      ingredients: "Pasteurized Non Fat Milk, Pasteurized Sweet Cream Buttermilk, Liquid Sugar (Sugar, Water), Pasteurized and Cultured Non Fat Milk, Corn Syrup, Peanut Butter (Peanuts, Salt, Hydrogenated Vegetable Oils (Rapeseed and Cottonseed)), Whey, Cream, Contains Less Than 1% Of Non Fat Dry Milk, Caramel Color, Mono- & Diglycerides, Cellulose Gum, Guar Gum, Natural and Artificial Flavors, Modified Food Starch, Carrageenan, Pectin. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
      calories: "120",
      calories_from_fat: "35",
      total_fat: "4",
      saturated_fat: "1.5",
      trans_fat: "0",
      cholesterol: "5",
      sodium: "90",
      total_carbohydrate: "19",
      dietary_fiber: "1",
      sugar: "14",
      sugar_alcohols: "0",
      protein: "4",
      vitamin_a: "2",
      vitamin_c: "0",
      calcium: "10",
      iron: "0",
      )

      Flavor.create(
       name: "Mango Sunrise",
       url: "http://1.imimg.com/data/P/4/MY-860281/Totapuri-Mango-Pulp_250x250.jpg",
       non_dairy: false,
       ingredients: "Water, Sugar, Corn Syrup, Mango Base [Water, Pear Juice Concentrate, Mango Juice Concentrate, Mango Puree, Orange Juice Concentrate, Natural Flavors, Citric Acid, Xanthan Gum, Annatto Extract (for color)], Citric Acid, Pectin, Natural Flavor, Fruit juice, Vegetable Juice and Turmeric (for color).",
       calories: "80",
       calories_from_fat: "0",
       total_fat: "0",
       saturated_fat: "0",
       trans_fat: "0",
       cholesterol: "0",
       sodium: "0",
       total_carbohydrate: "21",
       dietary_fiber: "0",
       sugar: "15",
       sugar_alcohols: "0",
       protein: "0",
       vitamin_a: "2",
       vitamin_c: "0",
       calcium: "0",
       iron: "0",
       )

       Flavor.create(
        name: "Pink Lemonade",
        url: "http://www.yogurt-land.com/wp-content/uploads/2014/09/Pink-Lemonade-Sorbet.png",
        non_dairy: false,
        ingredients: "Water, Sugar, Corn Syrup, Lemonade Base (Concentrated Lemon Juice, Water, Lemon Pulp Cells and Lemon Oil), Pectin, Natural Flavor, Fruit Juice and Vegetable Juice (for color).",
        calories: "80",
        calories_from_fat: "0",
        total_fat: "0",
        saturated_fat: "0",
        trans_fat: "0",
        cholesterol: "0",
        sodium: "0",
        total_carbohydrate: "21",
        dietary_fiber: "0",
        sugar: "15",
        sugar_alcohols: "0",
        protein: "0",
        vitamin_a: "0",
        vitamin_c: "4",
        calcium: "0",
        iron: "0",
        )

        Flavor.create(
         name: "Black Cherry Greek",
         url: "http://www.atwistonolives.com/shop/images/1406/Aged+Black+Cherry+Balsamic+Vinegar.jpg",
         non_dairy: false,
         ingredients: "Pasteurized and Cultured Skim Milk, Sugar, Nonfat Dry Milk, Cherry Base (Pear, Apple, Clarified Pineapple and Cherry Juice Concentrates, Water, Plum and Elderberry Juice Concentrates, Malic Acid, Natural Flavors), Corn Syrup, Milk Protein, Whey, Natural Flavor, Food Starch, Carrageenan, Pectin, Fruit and Vegetable Juice for Color, Purified Stevia Extract. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
         calories: "100",
         calories_from_fat: "0",
         total_fat: "0",
         saturated_fat: "0",
         trans_fat: "0",
         cholesterol: "0",
         sodium: "75",
         total_carbohydrate: "19",
         dietary_fiber: "0",
         sugar: "14",
         sugar_alcohols: "0",
         protein: "7",
         vitamin_a: "0",
         vitamin_c: "2",
         calcium: "15",
         iron: "0",
         )

         Flavor.create(
          name: "Original Tart",
          url: "http://bluehillyogurt.com/sites/default/files/images/Milk-Jar.jpg",
          non_dairy: false,
          ingredients: "Pasteurized and Cultured Skim Milk, Sugar, Corn Syrup, Whey, Nonfat Dry Milk, Lemon Juice Concentrate, Citric Acid, Food Starch, Carrageenan, Pectin, Natural Flavor. Contains the following live and active cultures: S. thermophilus, L. bulgaricus, L. lactis, L. acidophilus and Bifidobacterium.",
          calories: "90",
          calories_from_fat: "0",
          total_fat: "0",
          saturated_fat: "0",
          trans_fat: "0",
          cholesterol: "0",
          sodium: "65",
          total_carbohydrate: "20",
          dietary_fiber: "0",
          sugar: "15",
          sugar_alcohols: "0",
          protein: "3",
          vitamin_a: "0",
          vitamin_c: "0",
          calcium: "10",
          iron: "0",
          )
